/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateFeaturedProductArgs } from "./CreateFeaturedProductArgs";
import { UpdateFeaturedProductArgs } from "./UpdateFeaturedProductArgs";
import { DeleteFeaturedProductArgs } from "./DeleteFeaturedProductArgs";
import { FeaturedProductFindManyArgs } from "./FeaturedProductFindManyArgs";
import { FeaturedProductFindUniqueArgs } from "./FeaturedProductFindUniqueArgs";
import { FeaturedProduct } from "./FeaturedProduct";
import { Product } from "../../product/base/Product";
import { FeaturedProductService } from "../featuredProduct.service";

@graphql.Resolver(() => FeaturedProduct)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class FeaturedProductResolverBase {
  constructor(
    protected readonly service: FeaturedProductService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "FeaturedProduct",
    action: "read",
    possession: "any",
  })
  async _featuredProductsMeta(
    @graphql.Args() args: FeaturedProductFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [FeaturedProduct])
  @nestAccessControl.UseRoles({
    resource: "FeaturedProduct",
    action: "read",
    possession: "any",
  })
  async featuredProducts(
    @graphql.Args() args: FeaturedProductFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FeaturedProduct[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "FeaturedProduct",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => FeaturedProduct, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FeaturedProduct",
    action: "read",
    possession: "own",
  })
  async featuredProduct(
    @graphql.Args() args: FeaturedProductFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FeaturedProduct | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "FeaturedProduct",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => FeaturedProduct)
  @nestAccessControl.UseRoles({
    resource: "FeaturedProduct",
    action: "create",
    possession: "any",
  })
  async createFeaturedProduct(
    @graphql.Args() args: CreateFeaturedProductArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FeaturedProduct> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "FeaturedProduct",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"FeaturedProduct"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        product: {
          connect: args.data.product,
        },
      },
    });
  }

  @graphql.Mutation(() => FeaturedProduct)
  @nestAccessControl.UseRoles({
    resource: "FeaturedProduct",
    action: "update",
    possession: "any",
  })
  async updateFeaturedProduct(
    @graphql.Args() args: UpdateFeaturedProductArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FeaturedProduct | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "FeaturedProduct",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"FeaturedProduct"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          product: {
            connect: args.data.product,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FeaturedProduct)
  @nestAccessControl.UseRoles({
    resource: "FeaturedProduct",
    action: "delete",
    possession: "any",
  })
  async deleteFeaturedProduct(
    @graphql.Args() args: DeleteFeaturedProductArgs
  ): Promise<FeaturedProduct | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Product, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FeaturedProduct",
    action: "read",
    possession: "any",
  })
  async product(
    @graphql.Parent() parent: FeaturedProduct,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Product | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Product",
    });
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
